### ISSUE TITLE
Fails on the build-deploy

### ISSUE THREAD

**Issue by kyler-hyuna** [metcalfc/docker-action-examples#6]
Hey man, thanks for your example. Having some trouble trying to apply this to an org and private repo.

The login works, but it fails for me at the build-and-deploy step with `401 unauthorized`

**Comment by metcalfc** [comment]
Thanks for the report. When I get a second I'll try it on a private fork. I know there are some bits of magic for private forks and whatnot.

**Comment by metcalfc** [comment]
Point of clarification is the 401 for Hub or GHCR?

**Comment by kyler-hyuna** [comment]
GHCR

**Comment by metcalfc** [comment]
Sorry about the delay. I think that we would have better luck moving this to the community slack. http://dockr.ly/slack #github-actions
